TOPLEVEL_LANG = verilog

VERILOG_SOURCES = ../rtl/gf_mult3.v ../rtl/gf_mult2.v

TOPLEVEL = gf_mult3

COCOTB_TEST_MODULES = test_gf_mult3

SIM = icarus

include $(shell cocotb-config --makefiles)/Makefile.sim
